CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  login VARCHAR(60) NOT NULL UNIQUE,
  password CHAR(60) NOT NULL,
  name VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL
);
